require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  TargetRubyVersion: 2.7.8
  NewCops: enable

RSpec/MultipleExpectations: 
    Enabled: false

Style/Documentation:
  Enabled: false